name: ecommerce_application

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  shared_preferences: ^2.0.5
  image_picker: ^0.7.3
  firebase_storage: ^8.0.1
  firebase_core: ^1.0.2
  provider: ^5.0.0-nullsafety.5
  path_provider: ^2.0.2
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_phone_direct_caller: 
  cupertino_icons: ^1.0.1
  get: ^4.1.4
  async: ^2.5.0
  wc_form_validators: ^1.0.0
  flutter_spinkit: ^5.0.0
  pin_code_fields: ^7.1.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
